---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: healthcare
  template:
    metadata:
      labels:
        app: healthcare
    spec:
      containers:
        - name: healthcare
          image: snehaldhul/healthcare-image:latest
          ports:
            - containerPort: 8089
          env:
            - name: PORT
              value: "8089"
---
apiVersion: v1
kind: Service
metadata:
  name: healthcare
spec:
  type: NodePort
  ports:
    - port: 8089
      targetPort: 8089
  selector:
    app: healthcare
